app-name: Example0
bundle-id: com.example.example0
source-dir: Sources
resources-dir: Resources
deployment-target: 15.0
swift-version: 6
modules:
  - ModuleA
plist:
  version: "1.0.0"
  build-number: "1"
  info-plist:
    launch-screen: true
    required-device-capabilities:
      - arm64
      - metal
    supported-orientations:
      - UIInterfaceOrientationPortrait
    custom-entries:
      UIViewControllerBasedStatusBarAppearance: false
